package org.foreverempty.coosocial.content;

public enum GroupPermission {
    GROUP_VIEW,
    GROUP_EDIT_INFO,
    GROUP_EDIT_NOTICE,
    GROUP_INVITE_MEMBER,
    GROUP_REVIEW_INVITE,
    GROUP_REVIEW_APPLY,
    GROUP_REMOVE_MEMBER,
    GROUP_ASSIGN_TITLE,
    GROUP_MANAGE_TITLE,
    GROUP_SET_SUPER_ADMIN,
    GROUP_TRANSFER_OWNER,
    GROUP_EDIT_MEMBER_NICKNAME
}
