server:
  port: 8080 # 前端访问这个端口
spring:
  application:
    name: Coo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      server:
        webflux:
          routes:
            - id: auth_route
              uri: lb://Coo-auth # lb 代表 LoadBalance，去 Nacos 找 Coo-auth
              predicates:
                - Path=/api/auth/** # 凡是 /api/auth/ 开头的请求都发给 chat-auth
              filters:
                - StripPrefix=2
            - id: file_route
              uri: lb://Coo-file
              predicates:
                - Path=/api/file/**
              filters:
                - StripPrefix=2