server:
  port: 8080 # 前端访问这个端口
spring:
  application:
    name: Coo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      server:
        webflux:
          routes:
            - id: auth_route
              uri: lb://Coo-auth # lb 代表 LoadBalance，去 Nacos 找 Coo-auth
              predicates:
                - Path=/auth/** # 凡是 /auth/ 开头的请求都发给 chat-auth
              filters:
                - StripPrefix=1 # 转发时去掉第一个路径(auth)，比如 /auth/api/hello 变 /api/hello