server:
  port: 8084

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coo_chat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
